apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: mysql
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
