apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --provider=openshift
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    io.kompose.service: phpmyadmin
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: phpmyadmin
    spec:
      containers:
      - env:
        - name: PMA_HOST
          value: mysql
        - name: PMA_PORT
          value: "3306"
        image: ' '
        name: png-phpmyadmin
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /sessions
          name: phpmyadmin-claim0
      restartPolicy: Always
      volumes:
      - name: phpmyadmin-claim0
        persistentVolumeClaim:
          claimName: phpmyadmin-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - png-phpmyadmin
      from:
        kind: ImageStreamTag
        name: phpmyadmin:latest
    type: ImageChange
status: {}
