apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --provider=openshift
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    io.kompose.service: webserver
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: webserver
    spec:
      containers:
      - image: ' '
        name: png-webserver
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: webserver-claim0
        - mountPath: /usr/local/etc/php/php.ini
          name: webserver-claim1
        - mountPath: /etc/apache2/sites-enabled
          name: webserver-claim2
        - mountPath: /var/log/apache2
          name: webserver-claim3
      restartPolicy: Always
      volumes:
      - name: webserver-claim0
        persistentVolumeClaim:
          claimName: webserver-claim0
      - name: webserver-claim1
        persistentVolumeClaim:
          claimName: webserver-claim1
      - name: webserver-claim2
        persistentVolumeClaim:
          claimName: webserver-claim2
      - name: webserver-claim3
        persistentVolumeClaim:
          claimName: webserver-claim3
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - png-webserver
      from:
        kind: ImageStreamTag
        name: webserver:latest
    type: ImageChange
status: {}
